### ISSUE TITLE
not working on 0.8.13

### ISSUE THREAD

**Issue by Slabhub** [bsongOT/logseq-plugin-areas#2]

**Comment by CharlesChiuGit** [comment]
I believe u mean 0.8.12, and yes it's not working.

**Comment by CharlesChiuGit** [comment]
@bsongOT @YU000jp the "Editor button" still not working after upgrade to v1.0.2.

**Comment by charliie-dev** [comment]
maybe this plugin just won't work on windows...
![圖片](https://user-images.githubusercontent.com/32497323/208441793-64be8fb5-7242-484b-bad7-090638fa4fef.png)

**Comment by charliie-dev** [comment]
v1.0.1 finally works on the latest logseq (v0.8.13, windows)!
@bsongOT @YU000jp Thanks for your effort!
This is a very cool plugin to play with!
![圖片](https://user-images.githubusercontent.com/32497323/208654966-461c75ca-960d-4e02-8a97-0135b69f67b3.png)

**Comment by bsongOT** [comment]
Good. Thanks.
